### ISSUE TITLE
Fix auth issues

### ISSUE THREAD

**Issue by emmertarmin** [emmertarmin/bets#2]
- [x] Implement Auth persistence with cookies and bearer token in backend
- [x] add middleware to tell frondent whether user is logged in
- [x] fix never save user login state in build step 🤦‍♂️
- [x] make obvious to the eye if htmx response is same as last time

**Comment by ggfx** [comment]
I think we have to define which pages can most likely be static and which can not.
If majority can be static hybrid output seems to be good, otherwise I would suggest to choose output server for more dynamic content.
In case of the menu we might need to fetch menu from an ssr on-demand rendered api endpoint having export const prerender = false.

**Comment by emmertarmin** [comment]
> I think we have to define which pages can most likely be static and which can not. If majority can be static hybrid output seems to be good, otherwise I would suggest to choose output server for more dynamic content. In case of the menu we might need to fetch menu from an ssr on-demand rendered api endpoint having export const prerender = false.

Fixed: Changed rendering from `hybrid` to `server` -> every page is server rendered on demand, no page is prerendered.
